### ISSUE TITLE
How to group 10 checkboxes as a single 'value'

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#142]
Consider a list of checkboxes, needed to determine what to log (eg. https://github.com/SjonHortensius/pfsense/pull/134/files#diff-d81819b278631b4507cb24d41d3408d9R461)

This specific implementation uses multiple unnamed groups, but they are functionally 1 group. Currently, this would result in:
![screenshot-25338](https://cloud.githubusercontent.com/assets/1684987/7336898/1754b4a4-ec13-11e4-9cd1-696ed65ec850.png)

You could forcefully setWidth(10), but that results in:
![screenshot-25349](https://cloud.githubusercontent.com/assets/1684987/7336903/33962f12-ec13-11e4-9ec8-c86d29e5e460.png)

Which both suck. What you want is probably:
![screenshot-25289](https://cloud.githubusercontent.com/assets/1684987/7336906/42f21db8-ec13-11e4-83e1-950332796856.png)

This requires a pretty big change however; it puts all `<label><input></label>` in a single col-sm-10, separated by `<br/>`'s. Is this the correct bs structure for this?

**Comment by SjonHortensius** [comment]
Technically, I think I would implement this either by introducing a Form_Input::setVertical (which is read in Input::__toString), or introduce a Form_MultiCheckbox that overloads Input::__toString

**Comment by SanderVanLeeuwen** [comment]
There are probably two solutions. The first is to print every checkbox in a separate form group, and add a `col-sm-offset-2` to all but the first group to fix the offset issues. This feels a bit bloated though.

Second solution is what you propose in your last example. The layout can probably be fixed by giving the labels a `display: block`; no `<br />`'s should be needed. I can take care of the relevant CSS if you make the necessary changes to the form class :)

**Comment by SjonHortensius** [comment]
Not all changes in pfSense.js were meant to go in this commit, but since we only call all functions once I decided to remove them in favor of calling them directly #FYI

**Comment by SanderVanLeeuwen** [comment]
Nice! Got a small tweak, see related commit.

**Comment by SjonHortensius** [comment]
Looks fine
