### ISSUE TITLE
File chooser ("Browse") control has alignment issues

### ISSUE THREAD

**Issue by sbeaver-netgate** [SjonHortensius/pfsense#180]
![pfsense_localdomain_-_diagnosticsadd_layer7_pattern](https://cloud.githubusercontent.com/assets/11539696/7540859/d8ff1cce-f57e-11e4-84d0-e7f259827e6c.png)

**Comment by SanderVanLeeuwen** [comment]
Seems to be a Bootstrap issue. File inputs are styled without `form-control` class. Probably because you can't influence the styling very much.

Updated the input class to remove this class. This leaves file inputs a little bit unstyled, but as intended by [bootstrap](http://getbootstrap.com/css/#forms).

**Comment by SjonHortensius** [comment]
LGTM
