### ISSUE TITLE
Forms with a single input, which layout

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#193]
Please compare /diag_tables.php and /diag_dump_states.php. Which of these do we want? I think we should choose a single layout for forms, and otherwise possibly use #166; but let's not have more than that

I'll update the Form.class to support any of these layouts.

**Comment by sbeaver-netgate** [comment]
Or compare diag_logs.php with diag_dump_states.php. Both list system values in a table, but they use different filter input styles.

I like the appearance of dump_states best, but I changed to that seen in diag_logs for all subsequent pages of that type because if was more consistent with the look and feel of the system. 

I could be persuaded either way.

**Comment by SanderVanLeeuwen** [comment]
My preference is to use the layout from `diag_tables.php`. I.e., with the CTA button outside of the form. This is consistent throughout the whole system, with the added bonus that future structure / layout changes will propagate on all pages.
