### ISSUE TITLE
Form Validator

### ISSUE THREAD

**Issue by thanegill** [SjonHortensius/pfsense#26]
Is it worth looking into something like this for form validation? (There's more that than just ip address validation.)
http://formvalidation.io/validators/ip/

I know that most of the form validation is done in php. But I believe that this would remove a lot of need for that.

**Comment by SanderVanLeeuwen** [comment]
I think it's a good idea to add javascript validation, and this plugin looks like a very good candidate. In my opinion though it would be in addition to the backend validation, not replacing it.

**Comment by SjonHortensius** [comment]
I agree with @SanderVanLeeuwen on this, we want to leave the backend-code alone; and client-side validation should not be the only validation performed, before piping user-input to a shell-command ;)

**Comment by SanderVanLeeuwen** [comment]
On second thought, it looks like formvalidation.io only offers paid plugins? I'm pretty sure it used to be free, but now a single developer licence is $25,- or $75,- for an organization license. And even then I'm not sure about the license agreement and pfSense's opinion about using a paid plugin. Bummer, because it's the most versatile (bootstrap based) plugin out there.

Other candidates are http://1000hz.github.io/bootstrap-validator/ and http://reactiveraven.github.io/jqBootstrapValidation/, but they only offer basic validators which means we'll have to add all sorts of regexes to validate IP addresses, MAC addresses, etc. I'll have to give this a bit more thought :P

**Comment by thanegill** [comment]
That's a shame. I do agree that any server side validation should stay in place. My vote is for jqBoootstrapValidation. Seems simple. Just add attributes with a message and a regexp.

**Comment by thanegill** [comment]
Same as #28. Save this for another release.
