### ISSUE TITLE
Checkbox + Input in 1 group = offset issue

### ISSUE THREAD

**Issue by SjonHortensius** [SjonHortensius/pfsense#35]
Visible in /system_authservers.php?act=new; possibly caused by .checkbox.col-sm-5
![screenshot-27000](https://cloud.githubusercontent.com/assets/1684987/6770347/cc3c6b4e-d0bd-11e4-9a2a-0658970975d2.png)

**Comment by thanegill** [comment]
Would something like this work better?

http://getbootstrap.com/components/#input-groups-checkboxes-radios

With a data-toggle to disabled.

**Comment by SjonHortensius** [comment]
Yeah that might work when there is only a single input but fails where there are multiple. I think this is caused by us putting the checkbox class on the parent `DIV` instead of the actual input

**Comment by SanderVanLeeuwen** [comment]
In this particular example, the layout issues are caused by two factors:
- The checkbox doesn't have a label because the description is empty. Apparently, bootstrap doesn't really handle this very well.
- The `collapse` class is added to the input (`ldap_extended_query`) instead of the container. Normally the `form-group` is the container, but in this case it should be the `col-sm-5` wrapper. Makes more sense anyway, because that would toggle the `help-block` alongside with the input.

**Comment by SjonHortensius** [comment]
Has already been fixed
